### ISSUE TITLE
How can I change device emulator (from mobile to desktop) in this code?

### ISSUE THREAD

**Issue by SudhansuSD** [abhinaba1080/protractor-lighthouse-integration#2]

**Comment by abhinaba-ghosh** [comment]
@SudhansuSD 

sorry for replaying so late. Will you mind to share a small code setup, so that i can deep dive. Let me know if you already  got the solution.

**Comment by SudhansuSD** [comment]
Issue solved

**Comment by abhinaba-ghosh** [comment]
Hi @SudhansuSD, can you tell us how you have solved the issue. It may be helpful for others.

**Comment by SudhansuSD** [comment]
Hi @abhinaba-ghosh ,
I just added the following lines in lighthouse.helper.ts:
// To run audit in desktop
const config = require('lighthouse/lighthouse-core/config/lr-desktop-config.js');    
//To run audit in mobile device
const config = require('lighthouse/lighthouse-core/config/lr-mobile-config.js');

**Comment by abhinaba-ghosh** [comment]
Hi @SudhansuSD It is very charming that you have managed to create separate necessary configurations. Can you provide the file details which you kept inside the ```config``` folder? You can also raise a PR with the same. It will help people to taste the flexibility.

**Comment by SudhansuSD** [comment]
Hi @abhinaba-ghosh , 
Actually for this there is no need of config folder. These are already available in node_module/lighthouse.
So just add the line and run the one you want to.That's it.
