### ISSUE TITLE
unable to run npm install 

### ISSUE THREAD

**Issue by SudhansuSD** [abhinaba1080/protractor-lighthouse-integration#3]
I cloned this project. However, I'm unable to run or update npm 
I ran command npm install and I got following error:
npm ERR! code EISGIT
npm ERR! path C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\homluvPerf\homluv_performance_automation\node_modules\lighthouse
npm ERR! git C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\homluvPerf\homluv_performance_automation\node_modules\lighthouse: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\homluvPerf\homluv_performance_automation\node_modules\lighthouse
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

**Comment by abhinaba-ghosh** [comment]
Hi @SudhansuSD . After cloning the project, you need ```change directory``` (cd) to the project and then run ```npm install```

**Comment by abhinaba-ghosh** [comment]
Hey @SudhansuSD , maybe this thread will help you https://github.com/APSL/react-native-version-number/issues/13

Let me know if this works!

**Comment by SudhansuSD** [comment]
It didn't work for me. So I had to remove node_module folder and install npm again and now it's working
